### ISSUE TITLE
Random Php Script Request...

### ISSUE THREAD

**Issue by Helpmetoday** [jonbellah/jonbellah.com#3]
Hello,

I have been searching all over the place for a php script where I can display a random image from a folder of images (non-sequential png images)  and only display one  image every 24 hours...A Pic of the Day script in php if you will..Can you point me to a free one or make one of those scripts?

Brian

**Comment by Helpmetoday** [comment]
I have decided to use your random php script but I cannot figure out how to set a link for each of the images, is that even possible?

**Comment by jonbellah** [comment]
In order to persist the randomly selected image across visits, as it seems you want to do from your question, you'll need to use a database of some kind. 

As for setting a link, you can wrap your randomly selected image with a link tag and then select a random link. In that case, you'll most likely want to use a [switch statement](http://php.net/manual/en/control-structures.switch.php).

Something like:
```
$i = rand(1,7);

switch ($i) {
    case 1:
        echo "<a href='http://test1.com'><img src='http://www.example.com/images/image-1.jpg'></a>";
        break;
    case 2:
        echo "<a href='http://test2.com'><img src='http://www.example.com/images/image-2.jpg'></a>";
        break;
}
```
